In [5]:


import numpy as np

#Creating a 1D array from a list
arr1 = np.array([1,2,3,4,5])
print(arr1)

#Creating a 2D array from a list of lists
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

"""# Creating Arrays with Functions"""

zeros = np.zeros((3,4))
print(zeros)

ones = np.ones((2,3))
print(ones)

# Creating an array with a range of values

range_arr = np.arange(10,20,2)
print(range_arr)

# Creating an array with random values

random_arr = np.random.rand(3, 3)
print(random_arr)

"""# Basic Array Operations - Element Wise Operations

"""

arr = np.array([1,2,3,4,5])

# Element-wise operations
print(arr + 2)
print(arr * 2)
print(arr - 1)
print(arr / 2)

arr = np.array([1,2,3,4,5])

print(np.sqrt(arr))
print(np.exp(arr))
print(np.log(arr))
print(np.sin(arr))

"""# Indexing and Slicing - Slicing"""

arr = np.array([1,2,3,4,5])

print(arr[1:4])
print(arr[:3])
print(arr[2:])

"""## Indexing and Slicing - Advanced Indexing"""

arr = np.array([1,2,3,4,5])

#Boolean indexing
print(arr[arr>3])

#Fancy indexing
indices = [0,2,4]
print(arr[indices])

"""# Reshaping and Transposing - Reshaping Arrays"""

arr = np.array([[1,2,3],[4,5,6]])
print(arr)

reshaped = arr.reshape((3,2))
print(reshaped)

"""# Reshaping and Transposing - Transposing Arrays"""

arr = np.array([[1,2,3],[4,5,6]])

transposed = arr.T
print(transposed)

"""# Aggregation Functions - Sum and Mean"""

arr = np.array([[1,2,3],[4,5,6]])

print(np.sum(arr))
print(np.sum(arr, axis=0)) #Sum along columns
print(np.sum(arr, axis=1)) #sum along rows
print(np.mean(arr)) #mean of all elements
print(np.argmin(arr)) #Index of minimum value
print(np.argmax(arr)) #Index of maximum value

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[10 12 14 16 18]
[[0.3872356  0.06561142 0.46030199]
 [0.20414477 0.55699572 0.22659075]
 [0.02803603 0.95834381 0.348412  ]]
[3 4 5 6 7]
[ 2  4  6  8 10]
[0 1 2 3 4]
[0.5 1.  1.5 2.  2.5]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[2 3 4]
[1 2 3]
[3 4 5]
[4 5]
[1 3 5]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 4]
 [2 5]
 [3 6]]
21
[5 7 9]
[ 6 15]
3.5
0
5
